### ISSUE TITLE
InGameUIのHp(ハート)のレイアウトの調整

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#174]
現状の配置では5つのハートが離れすぎていて(下記の画像のように)空白が生まれているので、隣接するようにレイアウトしてください。

![ca7a8ce4fe11ae17093e2df2823c9d4d](https://user-images.githubusercontent.com/83810925/208230127-6a07d4cd-0e26-47d5-88bf-8f9494ff08b5.png)

**Comment by ShinoharaRyuga** [comment]
パラメーターを使用したものに変更する
