### ISSUE TITLE
ボスステージの強欲なファンの修正

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#257]
・現状のボスステージでは、一番最後に待ち構えるボスの強欲なファンのみ前に走ってくるような挙動(※)になっているが、これでは味気ないと意見がありました。なのでボス以外の強欲なファンも同じような挙動を取るように修正してください。
ただし、壁になる強欲なファンの場合、一番下の段のファンのみが前に走ってくるような挙動をとるようにしてください。(人の上で走っているのは不自然なため。)

・現状のボスのサイズでは小さいという意見があったのでサイズをもっと大きくしてください。

※余談ですがプランナーさんたち曰く「某ガンダムの勝ち取りたいのやつ」とよばれているそうです。笑

**Comment by ShinoharaRyuga** [comment]
壁にはアニメーターの配列を用意する
