### ISSUE TITLE
失敗モーションの追加

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#259]
現状InGameにおいてダメージを受ける行為(Bad判定をとる、Outになってしまう)の際にUIの変化以外にフィードバックがないので、デザイナーさんが新規で上げてくださるイラストに、ダメージを受ける際に切り替えてください。

**Comment by ShinoharaRyuga** [comment]
参考資料
https://discord.com/channels/1023877975940268104/1030385034517028894/1056600680648953866

まだイラストが出来ていません。
イラストを差し替えれば完成というところまで作成お願いします。

ファンサのイラスト切り替えのようにインスペクターで表示している時間を変更できるようにして下さい。

BAD時は
ファンサのイラストに切り替わる→失敗のイラストに切り替わるようにして下さい。

OUT時は
失敗のイラストに切り替えて下さい。
