### ISSUE TITLE
リザルトUIの調整

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#260]
・現在のリザルト画面では画面左下側に「Excellent！」と文字を出しているスペースがあるが、デザイナーさんから「文字の後ろの枠をなくしてほしい」という意見がありました。
なのでExcellentの文字は残しつつ、枠の部分のみなくして後ろのアイドルの絵が見えるように調整してください。

・現在はスコアの表示に数字が回転するアニメーションをつけていますが、これを一番下の合計スコアを表示する時のみにし、それ以外のスコアは上から順にただ表示していくだけにしてください

追記：
・枠の削除に伴って、Excellentの文字にOutline(外枠)を追加してください。

**Comment by ShinoharaRyuga** [comment]
文字のアウトラインを追加する。

**Comment by ShinoharaRyuga** [comment]
「文字の後ろの枠をなくしてほしい」←赤線が引いてある部分を削除して下さい。

画像だと全ての文字にOutlineが入っていますが、
「Excellent！」「やっぱ俺って最高だわ！！」の部分だけにoutlineを入れて下さい。

![タスク](https://user-images.githubusercontent.com/86392648/209601505-369680df-724b-4cbc-be2b-a640d3fa23ac.png)
