### ISSUE TITLE
遊び方(チュートリアル)の修正

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#265]
まず補足としてチュートリアルの名前が「遊び方」に決まりました。

・現在の遊び方(チュートリアル)は難易度選択の画面右側に表示されるようになっていますが、リーダーの話し合いの中で「全画面表示の方がいい」という意見が多く見られました。なので下記の画像(※1,※2)を参考にして全画面にポップするように作ってください。

・そして遊び方(チュートリアル)を難易度選択画面以外でも見れるようにしたい(※3のような作りを想定)ので作った遊び方(チュートリアル)はプレハブ化して別のシーンでも使えるようにしてください。

![0d542f36e633cbe1](https://user-images.githubusercontent.com/83810925/209572144-689afbc5-88d0-44ef-9054-436113b79b22.jpg)
![20161029184703179](https://user-images.githubusercontent.com/83810925/209572304-77f8a035-ac0a-460c-81f2-57353674f41b.png)
(※1,※2)

![0d542f36e633cbe1](https://user-images.githubusercontent.com/83810925/209572842-85b2c3e0-ea58-4455-b7da-7dbdba37b9ba.jpg)
(※3)

**Comment by ShinoharaRyuga** [comment]
表示する機能は出来たので中身の部分を作成する
