### ISSUE TITLE
メニューの追加

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#266]
現在はメニューが存在せず、タイトルにストーリー、クレジット。難易度選択に遊び方(チュートリアル)がおかれていますが、メニューを作りそこからストーリー、遊び方、クレジット、(その他設定等々…)を見れる方がいいという意見がありました。
なのでボタンを押したら表示させるメニューを作り、そのメニューの中にストーリーや遊び方を表示するボタンを作ってください。(下記の画像参照)
![0d542f36e633cbe1](https://user-images.githubusercontent.com/83810925/209573975-cfdf6553-b3ce-4ced-b7f9-c1d6d45bbf08.jpg)

**Comment by ShinoharaRyuga** [comment]
ストーリーを表示を作成する

**Comment by ShinoharaRyuga** [comment]
ストーリー,　遊び方はステージ選択画面に遷移してから表示させる
