### ISSUE TITLE
ストーリー、遊び方(チュートリアル)の強制表示の追加

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#267]
・現在ストーリー、遊び方はそれぞれが置かれているボタンから表示するのみですが、「タイトルと難易度選択の間で強制表示させ、スキップをできるようにした方がいい」という意見がありました。
なので下記の画像画像を参考にして、ストーリーと遊び方を強制表示させるようにしてください。
![0d542f36e633cbe1](https://user-images.githubusercontent.com/83810925/209574598-59c30347-6d60-4bbf-b441-f02e57c7c9c2.jpg)

**Comment by ShinoharaRyuga** [comment]
ストーリー,　遊び方はステージ選択画面に遷移してから表示させる
