### ISSUE TITLE
アイテム生成順番のリストでエラーが出る問題を解決する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#278]
手動で生成順番を設定するモードで次に生成するアイテム情報がないとエラーが出る

**Comment by ShinoharaRyuga** [comment]
IndexOutが出た。
エラーが出るタイミングは...
・リストの要素数が0の時
・設定したアイテムを全て生成し終えた時

確認、デバッグお願いします。

**Comment by RyoMaeda2525** [comment]
リストを使用しない場合はbool型の「Random Generator」にチェックを入れれば解決します。
