### ISSUE TITLE
アウトゲーム部分の見た目改善

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#305]
・タイトル画面の「TAP TO START」の文字が見ずらいという意見がありました。(下記画像参照)
この「TAP TO START」の文字にアウトライン(外枠)をつけ、点滅のアニメーションを行うようにしてください。

アウトラインの色合い
https://discord.com/channels/1023877975940268104/1027877790533550161/1057942884571156480

<アウトラインについて>
https://ekulabo.com/text-mesh-pro-material

![2023-01-08](https://user-images.githubusercontent.com/83810925/211162208-4bb09569-a323-4682-9307-8ff0b9ea5381.png)

**Comment by H1jikata** [comment]
確認しました
