### ISSUE TITLE
ストーリーの変更調整

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#306]
〇背景変更
・ストーリー画面の背景をクレジットに使用している背景画像(画像１参照)と同じように作り変えてください。
〇タップで全文表示
・ストーリー画面の全文表示(現在のスキップボタンで行っている機能)をタップで行えるようにしてください。
〇強制表示時に画面を飛ばせるように
・ストーリー画面は現在「タイトルから難易度選択画面に進むときに強制表示」する方法と、「タイトル、メニュー画面にあるボタンを押したら表示」する方法の２パターンがあります。このうち「タイトルから難易度選択画面に進むときに強制表示」する際は右上にSKIPボタンを表示し、押されたら全文表示していなくても遊び方画面に進むようにしてください。
〇任意表示時に見た目調整
・ストーリーを「タイトル、メニュー画面にあるボタンを押したら表示」する際はSKIPボタンではなく「戻るボタン」が表示されるようにしてください。そして、押されたら画面を閉じるようにしてください。
〇閉じるボタンの仕様変更
・「閉じるボタン」(画像２参照)はなくし、タイトルの「TAP TO START」のように「NEXT」というテキストを置き、全文表示されてるときにタップされたら画面を閉じるようにしてください。
![2023-01-08 (1)](https://user-images.githubusercontent.com/83810925/211162643-31bd3f3a-fb7c-4a16-9194-7ba0c2fefbe8.png)
画像１
![2023-01-08 (2)](https://user-images.githubusercontent.com/83810925/211163097-ff667d6a-b8a4-4c85-8e24-c07261174d1e.png)
画像２

**Comment by ShinoharaRyuga** [comment]
- [ ] 背景の変更
- [ ] タップで全文を表示
- [ ] 強制表示時のスキップ機能
- [ ] 任意表示時に見た目調整
