### ISSUE TITLE
インゲームの機能の変更調整

### ISSUE THREAD

**Issue by RyuKento** [VGA-Team2022/idol-road#310]
〇カットインを行うコンボ数を設定できるようにする
・ファンサを続けて成功させ、コンボが重なった時にカットインを行うようになっています。カットインを行うコンボの数値を設定できるように修正してください。(例：一回目,5コンボ、二回目,10コンボ、三回目,40コンボ...)
※細かい数値の設定はプランナーに設定してもらいます。
〇アイテムの生成間隔を無制限に設定できるようにする
・アイテムの生成間隔は現在0~10に制限されていますが、プランナーさんから10秒以上の間隔を空けたいという意見がありました。なので無制限に設定できるようにするに変更してください。

**Comment by ShinoharaRyuga** [comment]
コンボについて補足説明

関連資料
https://docs.google.com/spreadsheets/d/1p_hVlgAJ9p46NuYBdzXLl0-_X8PwV9rC/edit#gid=1783326380&range=A1:D2

他のレベルデザイン用パラメーターのようにコンボ回数を決められるようにする。
現状は5コンボでイラストが出るようになっているがそれを可変にする。

〇設定させる値
・コンボ回数
・出せるイラスト

敵の生成順番を決めるscriptableobjectのような作りにしてください。

それに伴うイラストを表示させる機能も変更してください。

関連するクラス
GameManager
InGameUIController

期限は 1月 11日 13時まで　（早ければ早いほど良いです...）

**Comment by ShinoharaRyuga** [comment]
アイテム生成間隔についての補足説明
Range外してください。
