### ISSUE TITLE
ゲームシーンを管理するクラスの作成（InGameManager）

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#33]
●欲しい機能
・スーパーアイドルタイムに移るため機能→アイドルパワーを保持しておく変数も必要
・ゲーム終了時の関数→ゴール時や体力が０になった時に呼べるようにして欲しい

シングルトンパターンで作成をお願いしていましたがシングルトンパターンにしなくても大丈夫です。
（作成してもらったのに使用しなく申し訳ない）
現在はKillFun()という関数がありますがこの機能は別クラスに持たせるので大丈夫です。

**Comment by ShinoharaRyuga** [comment]
体力を管理する変数も用意お願いします。

**Comment by ryooout** [comment]
クラスの名前もInGameManagerにしたほうが良いですか？

**Comment by ShinoharaRyuga** [comment]
@ryooout 
クラス名はGameManagerのままで大丈夫です。
（後で変更をお願いするかもしれません。その時対応お願いします。）

**Comment by ShinoharaRyuga** [comment]
体力やゴールまでの距離をUIに反映させる

**Comment by ShinoharaRyuga** [comment]
リファクタリングしたい

**Comment by ShinoharaRyuga** [comment]
画面存在する敵のリストを作成する

**Comment by ShinoharaRyuga** [comment]
対象を切り替える機能を追加する
