### ISSUE TITLE
プロト　背景を作成する

### ISSUE THREAD

**Issue by ShinoharaRyuga** [VGA-Team2022/idol-road#4]
歩いている感を出せるような機能を作成してください。

道となる部分を移動させれば行けるような気がします。

**Comment by TsuguhikoOkada** [comment]
了解です。

**Comment by TsuguhikoOkada** [comment]
これから作成するスクロールパターン

1. 道と背景が1セットの絵を下に少しずつスクロールする方法
2. 道と背景が1個ずつバラバラで絵を下に少しずつスクロールする方法
